name: GoldmanPermissions
version: ${version}
main: lee.code.permissions.Permissions
api-version: 1.19
author: Lee
folia-supported: true
depend: [GoldmanColors, GoldmanPlayerData]
commands:
  setrank:
    description: Set a rank for a player.
    permission: permissions.command.setrank
    usage: "/setrank &f<player> <rank>"
  permission:
    description: Permission options to can execute for players.
    permission: permissions.command.permission
    usage: "/permission &f<player> <add/remove/check> <permission>"
  staffchat:
    description: Toggle staff chat channel.
    permission: permissions.command.staffchat
    aliases: [sc]
    usage: "/staffchat"
