name: GoldmanPermissions
version: ${version}
main: lee.code.permissions.Permissions
api-version: 1.19
author: Lee
folia-supported: true
depend: [GoldmanColors]
commands:
  setrank:
    description: Set a rank for a player.
    permission: permissions.command.setrank
    usage: "/setrank &f<player> <rank>"